services:
  relatorio-de-desempenho:
    build: .
    restart: unless-stopped
    ports:
      - "3456:3456"
    env_file:
      - .env
    volumes:
      - ./data:/app/data
    environment:
      - TZ=America/Sao_Paulo
